import base64

# mark the current email as read using id
def mark_as_read(service, msg_id):
    service.users().messages().modify(
        userId="me",
        id=msg_id,
        body={"removeLabelIds": ["UNREAD"]}
    ).execute()

# refactored for the second time to eliminate looped api calls
def read_emails(service, whitelist):
    relevant = []
    batch = service.new_batch_http_request()

    # only one call to api, executes when one or more emails meet query
    query = "is:unread newer_than:1d from:(" + " OR ".join(whitelist) + ")"
    results = service.users().messages().list(userId="me", q=query).execute()
    messages = results.get("messages", [])

    if not messages:
        return []

    # request_id is generated by injection by gmail api
    def callback(request_id, response, exception):
        if exception is None:
            relevant.append(response)

    for msg in messages:
        batch.add(
            service.users().messages().get(userId="me", id=msg["id"], format="full"),
            callback=callback
        )

    batch.execute() # execute the batch queue to be sent
    return relevant

# recursive helper function looping through body subparts, to get text/plain
def _extract_text(part): 
    mime = part.get("mimeType", "")
    if mime == "text/plain":
        data = part.get("body", {}).get("data")
        if data:
            return base64.urlsafe_b64decode(data).decode("utf-8")
    if mime.startswith("multipart/"):
        for subpart in part.get("parts", []):
            result = _extract_text(subpart)
            if result:
                return result
    return None

# Extracting email information ====================
def get_body(message):
    # recursive function to traverse mimetype text/plain
    return _extract_text(message["payload"])

def get_sender(message):
    headers = message["payload"]["headers"]
    for header in headers:
        if header["name"] == "From":
            return header["value"]
    return None

def get_subject(message):
    headers = message["payload"]["headers"]
    for header in headers:
        if header["name"] == "Subject":
            return header["value"]
    return None

def get_thread_id(message):
    return message["threadId"]

def get_message_id(message):
    headers = message["payload"]["headers"]
    for header in headers:
        if header["name"] == "Message-ID":
            return header["value"]
    return ""